### PR TITLE
Tag for paper JXB

### PR DESCRIPTION
**Pull request by pradal**
Update all submodules to the tag  **paper_JXBot_2020**
Check if everything is OK.

### CODE REVIEW

**Comment by mngauthier** [comment]
Thanks Christophe for the branch. I will create the tag.
Now, if we create a doi based on the tag, it will link to zip file with empty sub-modules.
Do you know a solution ?
For this branch only, could we create real sub-directories instead of the sub-modules elongwheat, cnwheat, etc. ?

**Comment by pradal** [comment]
Are you sure?
I do not think so. I think that the doi is done using git fetch with 
specific options.
However, I will check.
Stay tuned.
Christophe

Le 17/04/2020 à 17:39, Marion Gauthier a écrit :

**Comment by rbarillot** [comment]
if the doi works as the download button and provides an zip file, then I think the submodules will be empty. See here for instance https://github.com/dear-github/dear-github/issues/214

**Comment by pradal** [comment]
You are right.
But you can upload directly on Zenodo an archive.
I will create it and send it to you.
During this time, you can enter the information (authors, keywords, ...) on Zenodo to have a doi:
https://zenodo.org/deposit/new

**Comment by rbarillot** [comment]
Other question: how should we deal with dependencies like python, scipy, pandas, numpy but also with Openalea pkg (here adel and caribu). Where should it be mentioned which dependencies were used?

**Comment by pradal** [comment]
In the README.md

Le 17/04/2020 à 21:34, Romain Barillot a écrit :

**Pull request merged**
